#!/usr/bin/env bash
# Generate a udev rule that grants the logged-in user access to input devices.
#
# Access is granted with TAG+="uaccess", the same mechanism logind uses for
# /dev/snd. It gives the device to whoever is logged in on the active seat,
# not to every user on the machine.
#
# Run this only if "periferia check" says the devices are not accessible.
#
#   bash scripts/gen-udev-rules.sh [PATTERN...] [--install]
#
#   PATTERN     keep only devices whose by-id name contains PATTERN
#   --install   write the rule and reload udev (asks for sudo)
#
# Without a pattern every keyboard and every extra input interface is
# included, which usually means the mouse as well. Flags and patterns may be
# given in any order.
set -euo pipefail

cd "$(dirname "$0")/.."

BY_ID=${PERIFERIA_BY_ID:-/dev/input/by-id}
say() { printf '\033[1m==>\033[0m %s\n' "$1" >&2; }

# Flags and device name patterns share the command line, so they have to be
# pulled apart first. Checking only $1 meant "--install" after a pattern was
# treated as another pattern, and the rule was printed instead of installed.
install=0
patterns=()
for arg in "$@"; do
    case "$arg" in
        --install) install=1 ;;
        -h|--help)
            sed -n '2,16p' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        -*) echo "error: unknown option $arg" >&2; exit 1 ;;
        *) patterns+=("$arg") ;;
    esac
done
set -- "${patterns[@]+"${patterns[@]}"}"

if [ ! -d "$BY_ID" ]; then
    echo "error: $BY_ID does not exist." >&2
    echo "This usually means the command is not running on the real system," >&2
    echo "or inside a container." >&2
    exit 1
fi

mapfile -t links < <(
    find "$BY_ID" -maxdepth 1 -type l \
        \( -name '*-event-kbd' -o -name '*-event-if*' \) 2>/dev/null | sort
)

# The dedup below keeps the first link per vendor:product, so a keyboard has
# to be considered before the other interfaces of the same device. Sorting
# "event-if02" ahead of "event-kbd" used to label the rule after the wrong
# interface.
if [ "${#links[@]}" -gt 0 ]; then
    mapfile -t links < <(
        printf '%s\n' "${links[@]}" | awk '/event-kbd/ {kbd = kbd $0 "\n"; next} {other = other $0 "\n"} END {printf "%s%s", kbd, other}'
    )
fi

if [ "$#" -gt 0 ]; then
    filtered=()
    for link in "${links[@]}"; do
        base=$(basename "$link")
        for pattern in "$@"; do
            case "$base" in
                *"$pattern"*) filtered+=("$link"); break ;;
            esac
        done
    done
    if [ "${#filtered[@]}" -eq 0 ]; then
        echo "error: no device matches: $*" >&2
        echo "available:" >&2
        printf '  %s\n' "${links[@]##*/}" >&2
        exit 1
    fi
    links=("${filtered[@]}")
    say "filter: $# (matching: ${links[*]##*/})"
fi

if [ "${#links[@]}" -eq 0 ]; then
    echo "error: no keyboard-like devices in $BY_ID" >&2
    exit 1
fi

declare -A seen=()
pairs=()
example_node=

for link in "${links[@]}"; do
    node=$(readlink -f "$link")
    [ -e "$node" ] || continue

    props=$(udevadm info -q property -n "$node" 2>/dev/null || true)
    vendor=$(printf '%s\n' "$props" | sed -n 's/^ID_VENDOR_ID=//p' | head -1)
    product=$(printf '%s\n' "$props" | sed -n 's/^ID_MODEL_ID=//p' | head -1)

    if [ -z "$vendor" ] || [ -z "$product" ]; then
        say "skipping $node: could not read vendor/product"
        continue
    fi

    key="$vendor:$product"
    if [ -n "${seen[$key]:-}" ]; then
        continue
    fi
    seen[$key]=1
    pairs+=("$key|$(basename "$link")")
    # Kept for the hint printed after install, so it names a keyboard node
    # that was actually matched instead of a hardcoded one.
    if [ -z "$example_node" ]; then
        example_node="$node"
    fi
    say "found $key  ($(basename "$link"))"
done

if [ "${#pairs[@]}" -eq 0 ]; then
    echo "error: no usable vendor/product pairs" >&2
    exit 1
fi

rule=""
for entry in "${pairs[@]}"; do
    key="${entry%%|*}"
    label="${entry##*|}"
    vendor="${key%%:*}"
    product="${key##*:}"
    rule+=$(cat <<EOF

# $label, $key
    ACTION=="add|change", KERNEL=="event*", SUBSYSTEM=="input", \\
      ATTRS{idVendor}=="$vendor", ATTRS{idProduct}=="$product", \\
      TAG+="uaccess"
EOF
)
done

out=$(cat <<EOF
# Generated by scripts/gen-udev-rules.sh
#
# Grants the logged-in user read and write access to these input devices.
# Review it before installing: it names the keyboards it found.
$rule
EOF
)

if [ "$install" -eq 1 ]; then
    dest=${PERIFERIA_RULES_DEST:-/etc/udev/rules.d/10-periferia.rules}
    # On a current rpm-ostree deployment /etc is writable by the admin, and
    # "rpm-ostree override create" no longer exists at all (it was replaced by
    # override remove/replace/reset). So write the file first and only fall
    # back to an override when that is refused.
    used_override=0
    if printf '%s\n' "$out" | sudo tee "$dest" >/dev/null 2>&1; then
        say "wrote $dest"
    else
        say "$dest is not writable, trying an rpm-ostree override"
        if ! command -v rpm-ostree >/dev/null 2>&1; then
            echo "error: $dest is not writable and rpm-ostree is not present" >&2
            exit 1
        fi
        if ! rpm-ostree override create --admin "$dest" 2>/dev/null; then
            echo "error: $dest is not writable and this rpm-ostree has no" >&2
            echo "  'override create'. On this system /etc is managed by the" >&2
            echo "  deployment, so the rule has to be placed another way." >&2
            exit 1
        fi
        used_override=1
        if ! printf '%s\n' "$out" | sudo tee "$dest" >/dev/null; then
            echo "error: the override was created but the write still failed" >&2
            exit 1
        fi
        say "wrote $dest inside an override"
    fi
    sudo udevadm control --reload-rules
    sudo udevadm trigger --subsystem-match=input
    echo >&2
    echo "installed $dest and re-triggered the input subsystem" >&2
    echo >&2
    echo "Now check whether the access appeared:" >&2
    if [ -n "$example_node" ]; then
        echo "  getfacl -p '$example_node' | grep -q \"\$(id -un)\" && echo 'ACL present' || echo 'no ACL yet'" >&2
    fi
    echo "  periferia check" >&2
    echo >&2
    echo "If the ACL is still missing, log out and back in: uaccess is applied" >&2
    echo "when the seat claims the device, which only happens on a new session." >&2
    echo >&2
    if [ "$used_override" -eq 1 ]; then
        cat >&2 <<'EOF'
The rule now lives in an rpm-ostree override, so it survives updates.
To undo it:

  sudo rpm-ostree override remove /etc/udev/rules.d/10-periferia.rules
EOF
    else
        cat >&2 <<EOF
To undo it:

  sudo rm -f $dest
EOF
    fi
else
    printf '%s\n' "$out"
    cat >&2 <<'EOF'

Not installed. Run with --install to write it, or review it first:

  bash scripts/gen-udev-rules.sh${patterns:+ ${patterns[*]}} --install
EOF
fi
