#!/usr/bin/env bash
# Generate a udev rule that grants the logged-in user access to input devices.
#
# Access is granted with TAG+="uaccess", the same mechanism logind uses for
# /dev/snd. It gives the device to whoever is logged in on the active seat,
# not to every user on the machine.
#
# Run this only if "periferia check" says the devices are not accessible.
#
#   bash scripts/gen-udev-rules.sh            # print the rule
#   bash scripts/gen-udev-rules.sh --install  # write it and reload udev
set -euo pipefail

cd "$(dirname "$0")/.."

BY_ID=/dev/input/by-id
say() { printf '\033[1m==>\033[0m %s\n' "$1" >&2; }

if [ ! -d "$BY_ID" ]; then
    echo "error: $BY_ID does not exist." >&2
    echo "This usually means the command is not running on the real system," >&2
    echo "or inside a container." >&2
    exit 1
fi

mapfile -t links < <(
    find "$BY_ID" -maxdepth 1 -type l \
        \( -name '*-event-kbd' -o -name '*-event-if*' \) 2>/dev/null | sort
)

if [ "${#links[@]}" -eq 0 ]; then
    echo "error: no keyboard-like devices in $BY_ID" >&2
    exit 1
fi

declare -A seen=()
pairs=()

for link in "${links[@]}"; do
    node=$(readlink -f "$link")
    [ -e "$node" ] || continue

    props=$(udevadm info -q property -n "$node" 2>/dev/null || true)
    vendor=$(printf '%s\n' "$props" | sed -n 's/^ID_VENDOR_ID=//p' | head -1)
    product=$(printf '%s\n' "$props" | sed -n 's/^ID_MODEL_ID=//p' | head -1)

    if [ -z "$vendor" ] || [ -z "$product" ]; then
        say "skipping $node: could not read vendor/product"
        continue
    fi

    key="$vendor:$product"
    if [ -n "${seen[$key]:-}" ]; then
        continue
    fi
    seen[$key]=1
    pairs+=("$key|$(basename "$link")")
    say "found $key  ($(basename "$link"))"
done

if [ "${#pairs[@]}" -eq 0 ]; then
    echo "error: no usable vendor/product pairs" >&2
    exit 1
fi

rule=""
for entry in "${pairs[@]}"; do
    key="${entry%%|*}"
    label="${entry##*|}"
    vendor="${key%%:*}"
    product="${key##*:}"
    rule+=$(cat <<EOF

# $label, $key
    ACTION=="add|change", KERNEL=="event*", SUBSYSTEM=="input", \\
      ATTRS{idVendor}=="$vendor", ATTRS{idProduct}=="$product", \\
      TAG+="uaccess"
EOF
)
done

out=$(cat <<EOF
# Generated by scripts/gen-udev-rules.sh
#
# Grants the logged-in user read and write access to these input devices.
# Review it before installing: it names the keyboards it found.
$rule
EOF
)

if [ "${1:-}" = "--install" ]; then
    dest=/etc/udev/rules.d/10-periferia.rules
    if command -v rpm-ostree >/dev/null 2>&1; then
        # /etc is owned by the image on an ostree system, so the override has
        # to be created first or the copy below has nowhere to land.
        say "creating rpm-ostree override for $dest"
        sudo rpm-ostree override create --admin "$dest" || {
            echo "error: could not create the override" >&2
            exit 1
        }
    fi
    printf '%s\n' "$out" | sudo tee "$dest" >/dev/null
    sudo udevadm control --reload-rules
    sudo udevadm trigger --subsystem-match=input
    echo >&2
    echo "installed $dest and re-triggered the input subsystem" >&2
    echo >&2
    echo "Now check whether the access appeared:" >&2
    echo "  getfacl -p /dev/input/event5 2>/dev/null | grep -q "$(id -un)" && echo "ACL present" || echo "no ACL yet"" >&2
    echo "  periferia check" >&2
    echo >&2
    echo "If the ACL is still missing, log out and back in: uaccess is applied" >&2
    echo "when the seat claims the device, which only happens on a new session." >&2
    echo >&2
    if command -v rpm-ostree >/dev/null 2>&1; then
        cat >&2 <<'EOF'
The rule now lives in an rpm-ostree override, so it survives updates.
To undo it:

  sudo rpm-ostree override remove /etc/udev/rules.d/10-periferia.rules
EOF
    fi
else
    printf '%s\n' "$out"
    cat >&2 <<'EOF'

Not installed. Run with --install to write it, or review it first:

  bash scripts/gen-udev-rules.sh --install
EOF
fi
